# Generated by Django 2.1.7 on 2019-06-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryWine',
            fields=[
                ('wine_id', models.IntegerField(primary_key=True, serialize=False)),
                ('color', models.TextField()),
                ('name', models.TextField()),
                ('wine_type_id', models.IntegerField(unique=True)),
                ('wine_type', models.TextField()),
                ('producer_id', models.IntegerField(unique=True)),
                ('producer', models.TextField()),
                ('region_id', models.IntegerField(unique=True)),
                ('region', models.TextField()),
                ('vintage', models.IntegerField()),
                ('last_purchase_date', models.IntegerField()),
                ('inventory_cnt', models.IntegerField()),
                ('last_price', models.FloatField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('avg_price', models.FloatField()),
                ('avg_vintage', models.FloatField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
