language: rust
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/git
  - rm -rf /home/travis/.cargo/registry
matrix:
  include:
    - os: linux
      rust: nightly-2020-06-23
      env: TARGET=x86_64-unknown-linux-gnu

env:
  global:
    - HOST=x86_64-unknown-linux-gnu
    - NODE_VERSION="12.14.1"

sudo: required

before_install:
  - nvm install $NODE_VERSION

script:
  - bash scripts/build.sh
  - bash scripts/test.sh
  - bash scripts/lint.sh

notifications:
  email:
    on_success: never
