language: rust
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/git
  - rm -rf /home/travis/.cargo/registry
matrix:
  include:
    - os: linux
      rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu

env:
  global:
    - HOST=x86_64-unknown-linux-gnu

sudo: required

install:
  - sudo apt update

script:
  - bash scripts/build.sh
  - bash scripts/test.sh
  - bash scripts/lint.sh

notifications:
  email:
    on_success: never
