[package]
name = "vinoteca"
version = "5.0.0"
authors = ["Carter Green <cartergr@usc.edu>"]
readme = "../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
rocket = "0.4.2"
rocket_codegen = "0.4.2"
diesel = { version = "1.0", features = ["sqlite"] }
dotenv = "0.9"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json", "diesel_sqlite_pool", "serve"]

[dependencies.askama]
version = "0.8"
features = ["with-rocket"]
