[package]
name = "vinoteca"
description = "Wine purchase tracker"
repository = "https://github.com/threecgreen/vinoteca"
version = "6.1.3"
edition = "2018"
authors = ["Carter Green <cartergr@usc.edu>"]
readme = "./README.md"
license = "MIT"
default-run = "vinoteca"
categories = ["web-programming"]

[dependencies]
# Password encryption
bcrypt = "0.9.0"
# Datetime functionality
chrono = { version = "0.4.19", features = ["serde"] }
# basic ORM
diesel = { version = "1.4.5", features = ["postgres", "chrono"] }
diesel_migrations = "1.4.0"
# Image handling
image = "0.23.12"
kamadak-exif = "0.5.2"
lazy_static = "1.4.0"
log = "0.4.11"
rocket_codegen = "0.4.6"
rocket-multipart-form-data = "0.9.6"
# AWS S3 access
rust-s3 = "0.26.4"
# (De)serialization
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
time = "0.1.42"
uuid = { version = "0.8.1", features = ["v4"] }
# Input validation
validator = "0.12.0"
validator_derive = "0.12.0"

[dependencies.rocket]
version = "0.4.6"
default_features = false
features = ["private-cookies"]

[dependencies.rocket_contrib]
version = "0.4.6"
default-features = false
features = ["json", "diesel_postgres_pool"]

# Generate typescript type definitions from rust structs
[dependencies.typescript-definitions]
version = "0.1.10"
# Enable export in release build
features = ["export-typescript"]

[dev-dependencies]
mockall = "0.9.0"
