[package]
name = "vinoteca"
description = "Wine purchase tracker"
repository = "https://github.com/threecgreen/vinoteca"
version = "6.3.0"
edition = "2018"
authors = ["Carter Green <cartergr@usc.edu>"]
readme = "./README.md"
license = "MIT"
default-run = "vinoteca"
categories = ["web-programming"]

[dependencies]
# Password encryption
bcrypt = "0.9.0"
# Datetime functionality
chrono = { version = "0.4.19", features = ["serde"] }
# basic ORM
diesel = { version = "1.4.5", features = ["postgres", "chrono"] }
diesel_migrations = "1.4.0"
# Image handling
image = "0.23.12"
kamadak-exif = "0.5.3"
lazy_static = "1.4.0"
log = "0.4.11"
# rocket_codegen = { git = "https://github.com/SergioBenitez/Rocket", version = "v0.5-pre" }
# rocket-multipart-form-data = { git = "https://github.com/impero-com/rocket-multipart-form-data", branch = "v0.5-pre" }
# AWS S3 access
rust-s3 = { version = "0.26.4", features = ["fail-on-err"] }
# (De)serialization
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
time = "0.2.25"
uuid = { version = "0.8.1", features = ["v4"] }
# Input validation
validator = "0.12.0"
validator_derive = "0.12.0"

[dependencies.rocket]
git = "https://github.com/SergioBenitez/Rocket"
branch = "v0.5-pre"
default_features = false
features = ["secrets", "json"]

[dependencies.rocket_sync_db_pools]
git = "https://github.com/SergioBenitez/Rocket"
branch = "v0.5-pre"
default-features = false
features = ["diesel_postgres_pool"]

# Generate typescript type definitions from rust structs
[dependencies.typescript-definitions]
git = "https://github.com/onelson/typescript-definitions"
branch = "no-debug-attrs"
# Enable export in release build
features = ["export-typescript"]

[dev-dependencies]
mockall = "0.9.0"
