[package]
name = "vinoteca"
version = "5.0.0"
authors = ["Carter Green <cartergr@usc.edu>"]
readme = "../README.md"
default-run = "server"

[dependencies]
chrono = "0.4"
rocket = "0.4.2"
rocket_codegen = "0.4.2"
diesel = { version = "1.4", features = ["sqlite"] }
dotenv = "0.15"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
validator = "0.10"
validator_derive = "0.10"
rocket-multipart-form-data = "0.7"
image = "0.22"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json", "diesel_sqlite_pool", "serve"]

[dependencies.askama]
version = "0.9"
features = ["with-rocket"]

[dependencies.typescript-definitions]
version = "0.1"
# Enable export in release build
features = ["export-typescript"]
