[package]
name = "vinoteca"
description = "Wine purchase tracker"
repository = "https://github.com/threecgreen/vinoteca"
version = "5.0.5"
authors = ["Carter Green <cartergr@usc.edu>"]
readme = "./README.md"
license = "MIT"
default-run = "vinoteca"

# For generating .deb file for Linux installs
[package.metadata.deb]
depends = "$auto, libsqlite3-dev"
assets = [
    ["target/release/vinoteca", "usr/local/bin/", "755"],
    ["web/static/vinoteca.bundle.js", "usr/local/share/vinoteca/", "644"],
    ["web/static/vinoteca.bundle.css", "usr/local/share/vinoteca/", "644"],
    ["web/static/vendors.bundle.js", "usr/local/share/vinoteca/", "644"],
    ["web/static/img/*", "usr/local/share/vinoteca/img/", "644"],
    ["web/static/img/flags/*", "usr/local/share/vinoteca/img/flags/", "644"],
    ["README.md", "usr/local/share/doc/vinoteca/README", "644"],
]

[dependencies]
chrono = "0.4"
rocket = "0.4.3"
rocket_codegen = "0.4.3"
diesel = { version = "1.4", features = ["sqlite"] }
dotenv = "0.15"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
time = "0.1.42"
validator = "0.10"
validator_derive = "0.10"
rocket-multipart-form-data = "0.8.1"
image = "0.23.0"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json", "diesel_sqlite_pool"]

[dependencies.askama]
version = "0.9"
features = ["with-rocket"]

[dependencies.typescript-definitions]
version = "0.1"
# Enable export in release build
features = ["export-typescript"]
