[package]
name = "vinoteca"
description = "Wine purchase tracker"
repository = "https://github.com/threecgreen/vinoteca"
version = "6.3.0"
edition = "2018"
authors = ["Carter Green <cartergr@usc.edu>"]
readme = "./README.md"
license = "MIT"
default-run = "vinoteca"
categories = ["web-programming"]

[dependencies]
# Password encryption
bcrypt = "0.9.0"
# Datetime functionality
chrono = { version = "0.4.19", features = ["serde"] }
# basic ORM
diesel = { version = "1.4.7", features = ["postgres", "chrono"] }
diesel_migrations = "1.4.0"
# Image handling
image = "0.23.14"
kamadak-exif = "0.5.4"
lazy_static = "1.4.0"
log = "0.4.14"
# AWS S3 access
rust-s3 = { version = "0.26.4", features = ["fail-on-err"] }
# (De)serialization
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
time = "0.2.27"
uuid = { version = "0.8.2", features = ["v4"] }
# Input validation
validator = "0.13.0"
validator_derive = "0.13.0"

[dependencies.rocket]
version = "0.5.0-rc.1"
default_features = false
features = ["secrets", "json"]

[dependencies.rocket_sync_db_pools]
version = "0.1.0-rc.1"
default-features = false
features = ["diesel_postgres_pool"]

# Generate typescript type definitions from rust structs
[dependencies.typescript-definitions]
git = "https://github.com/onelson/typescript-definitions"
branch = "no-debug-attrs"
# Enable export in release build
features = ["export-typescript"]

[dev-dependencies]
mockall = "0.9.1"
