name: vinoteca
channels:
  - defaults
dependencies:
  - ca-certificates=2018.03.07
  - certifi=2018.10.15
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libstdcxx-ng=8.2.0
  - ncurses=6.1
  - nodejs=10.13.0
  - openssl=1.1.1
  - pip=10.0.1
  - python=3.7.1
  - readline=7.0
  - setuptools=39.2.0
  - sqlite=3.25.3
  - tk=8.6.8
  - wheel=0.31.1
  - pip:
    - astroid==2.0.4
    - atomicwrites==1.2.1
    - colorlog==3.1.4
    - coverage==4.5.1
    - django==2.1.7
    - django-filter==2.0.0
    - djangorestframework==3.8.2
    - isort==4.3.4
    - lazy-object-proxy==1.3.1
    - mccabe==0.6.1
    - more-itertools==4.2.0
    - pbr==5.1.1
    - pillow==5.2.0
    - pluggy==0.7.1
    - py==1.5.4
    - pylint==2.1.1
    - pylint-django==2.0.2
    - pylint-plugin-utils==0.4
    - pytest==3.8.0
    - pytest-cov==2.6.0
    - pytest-django==3.4.2
    - pytest-mock==1.10.0
    - python-dateutil==2.6.1
    - pytz==2018.3
    - pyyaml==3.13
    - rope==0.11.0
    - six==1.11.0
    - sqlparse==0.2.4
    - wrapt==1.10.11
