name: vinoteca
channels:
  - defaults
dependencies:
  - ca-certificates=2019.10.16
  - certifi=2019.9.11
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libstdcxx-ng=8.2.0
  - ncurses=6.1
  - nodejs=10.13.0
  - openssl=1.1.1
  - python=3.7.1
  - readline=7.0
  - setuptools=39.2.0
  - sqlite=3.25.3
  - tk=8.6.8
  - wheel=0.31.1
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - astroid==2.2.5
    - atomicwrites==1.2.1
    - attrs==17.4.0
    - colorlog==3.1.4
    - coverage==4.5.1
    - django==2.2.4
    - django-debug-toolbar==1.8
    - django-filter==2.2.0
    - django-js-error-hook==0.6
    - djangorestframework==3.10.2
    - importlib-metadata==0.19
    - isort==4.3.4
    - lazy-object-proxy==1.3.1
    - mccabe==0.6.1
    - more-itertools==4.2.0
    - packaging==19.1
    - pbr==5.1.1
    - pillow==6.2.1
    - pip==18.1
    - pluggy==0.12.0
    - py==1.5.4
    - pylint==2.3.1
    - pylint-django==2.0.11
    - pylint-plugin-utils==0.5
    - pyparsing==2.4.2
    - pytest==5.1.1
    - pytest-cov==2.7.1
    - pytest-django==3.5.1
    - pytest-mock==1.10.0
    - python-dateutil==2.6.1
    - pytz==2018.3
    - pyyaml==3.13
    - rope==0.11.0
    - six==1.11.0
    - sqlparse==0.2.4
    - typed-ast==1.4.0
    - wcwidth==0.1.7
    - wrapt==1.10.11
    - zipp==0.6.0

