name: vinoteca
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2019.10.16
  - certifi=2019.9.11
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libstdcxx-ng=8.2.0
  - ncurses=6.1
  - nodejs=10.13.0
  - openssl=1.1.1
  - pip=19.3.1
  - python=3.8.0
  - readline=7.0
  - setuptools=42.0.1
  - sqlite=3.30.1
  - tk=8.6.8
  - wheel=0.33.6
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - astroid==2.3.3
    - attrs==19.3.0
    - colorlog==4.0.2
    - coverage==4.5.4
    - django==2.1.14
    - django-filter==2.2.0
    - djangorestframework==3.9.4
    - isort==4.3.21
    - lazy-object-proxy==1.4.3
    - mccabe==0.6.1
    - more-itertools==8.0.0
    - packaging==19.2
    - pillow==6.2.1
    - pluggy==0.13.1
    - py==1.8.0
    - pylint==2.4.4
    - pylint-django==2.0.13
    - pylint-plugin-utils==0.6
    - pyparsing==2.4.5
    - pytest==5.3.1
    - pytest-cov==2.6.1
    - pytest-django==3.7.0
    - pytest-mock==1.12.1
    - python-dateutil==2.6.1
    - pytz==2018.9
    - pyyaml==5.1.2
    - six==1.13.0
    - wcwidth==0.1.7
    - wrapt==1.11.2

