//! SeaORM Entity. Generated by sea-orm-codegen 0.4.1

pub mod prelude;

pub mod colors;
pub mod grapes;
pub mod producers;
pub mod purchases;
pub mod regions;
pub mod stores;
pub mod users;
pub mod viti_areas;
pub mod wine_grapes;
pub mod wine_types;
pub mod wines;
