//! SeaORM Entity. Generated by sea-orm-codegen 0.4.1

pub use super::colors::Entity as Color;
pub use super::grapes::Entity as Grapes;
pub use super::producers::Entity as Producers;
pub use super::purchases::Entity as Purchases;
pub use super::regions::Entity as Regions;
pub use super::stores::Entity as Stores;
pub use super::users::Entity as Users;
pub use super::viti_areas::Entity as VitiAreas;
pub use super::wine_grapes::Entity as WineGrapes;
pub use super::wine_types::Entity as WineTypes;
pub use super::wines::Entity as Wines;
