//! SeaORM Entity. Generated by sea-orm-codegen 0.4.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "regions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text", unique)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::producers::Entity")]
    Producers,
    #[sea_orm(has_many = "super::viti_areas::Entity")]
    VitiAreas,
}

impl Related<super::producers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Producers.def()
    }
}

impl Related<super::viti_areas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VitiAreas.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
