CREATE TABLE IF NOT EXISTS "wine_grapes" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "percent" integer NULL, "grape_id" integer NOT NULL REFERENCES "grapes" ("id") DEFERRABLE INITIALLY DEFERRED, "wine_id" integer NOT NULL REFERENCES "wines" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX IF NOT EXISTS "wine_grapes_grape_id_0e357a67" ON "wine_grapes" ("grape_id");
CREATE INDEX IF NOT EXISTS "wine_grapes_wine_id_c0ed5414" ON "wine_grapes" ("wine_id");
CREATE UNIQUE INDEX IF NOT EXISTS wine_grapes_wine_id_grape_id_772ad5ca_uniq ON "wine_grapes" ("wine_id", "grape_id");
CREATE TABLE IF NOT EXISTS "colors" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" text NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "grapes" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" text NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "purchases" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "price" real NULL, "quantity" integer NULL, "vintage" integer NULL, "memo" text NULL, "store_id" integer NULL REFERENCES "stores" ("id") DEFERRABLE INITIALLY DEFERRED, "wine_id" integer NOT NULL REFERENCES "wines" ("id") DEFERRABLE INITIALLY DEFERRED, "date" integer NULL);
CREATE INDEX IF NOT EXISTS "purchases_store_id_2563c769" ON "purchases" ("store_id");
CREATE INDEX IF NOT EXISTS "purchases_wine_id_7e3b7107" ON "purchases" ("wine_id");
CREATE INDEX IF NOT EXISTS "purchases_date_96e1e1f0" ON "purchases" ("date");
CREATE TABLE IF NOT EXISTS "stores" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" text NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "wine_types" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" text NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "viti_areas" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" text NOT NULL, "region_id" integer NOT NULL REFERENCES "regions" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX IF NOT EXISTS "viti_areas_name_56501cc0" ON "viti_areas" ("name");
CREATE INDEX IF NOT EXISTS "viti_areas_region_id_91a7d558" ON "viti_areas" ("region_id");
CREATE TABLE IF NOT EXISTS "regions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" text NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "producers" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" text NOT NULL UNIQUE, "region_id" integer NOT NULL REFERENCES "regions" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX IF NOT EXISTS "producers_region_id_a5a7ed5d" ON "producers" ("region_id");
CREATE TABLE IF NOT EXISTS "wines" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "description" text NULL, "notes" text NULL, "rating" integer NULL, "inventory" integer NOT NULL, "why" text NULL, "color_id" integer NOT NULL REFERENCES "colors" ("id") DEFERRABLE INITIALLY DEFERRED, "producer_id" integer NOT NULL REFERENCES "producers" ("id") DEFERRABLE INITIALLY DEFERRED, "viti_area_id" integer NULL REFERENCES "viti_areas" ("id") DEFERRABLE INITIALLY DEFERRED, "name" text NULL, "wine_type_id" integer NOT NULL REFERENCES "wine_types" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX IF NOT EXISTS "wines_inventory_7cc76efa" ON "wines" ("inventory");
CREATE INDEX IF NOT EXISTS "wines_color_id_86d88962" ON "wines" ("color_id");
CREATE INDEX IF NOT EXISTS "wines_producer_id_bbb958aa" ON "wines" ("producer_id");
CREATE INDEX IF NOT EXISTS "wines_viti_area_id_26f131c8" ON "wines" ("viti_area_id");
CREATE INDEX IF NOT EXISTS "wines_wine_type_id_6b4d81d9" ON "wines" ("wine_type_id");
