# Generated by Django 2.0.5 on 2018-05-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinoteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wines',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
