# Generated by Django 2.0.5 on 2018-07-06 04:53
# Deletes duplicate Viti Area 'Russian River Valley'

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinoteca', '0002_wines_name'),
    ]

    operations = [
        migrations.RunSQL([
            "UPDATE wines SET viti_area_id = 4 WHERE viti_area_id = 12;",
            "DELETE FROM viti_areas WHERE id = 12;",
        ])
    ]
