# Generated by Django 2.0.5 on 2018-07-06 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinoteca', '0004_move_remaining_additional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wines',
            name='additional',
        ),
        migrations.DeleteModel(
            name='Additionals',
        ),
    ]
