# Generated by Django 2.0.5 on 2018-07-06 20:44
# Convert all images to PNG to fix rotation issue

from django.conf import settings
from django.db import migrations
from pathlib import Path
from vinoteca.image import UserImage


def convert_all_images(apps, schema_editor):
    """Convert all images in media/ to PNG files to fix rotation issue."""
    media_folder = Path(settings.MEDIA_ROOT)
    # Iterate through image files and ignore '.gitignore'
    for file in media_folder.iterdir():
        if file.is_file() and file.name != ".gitignore":
            UserImage(file).convert_to_png()


class Migration(migrations.Migration):

    dependencies = [
        ('vinoteca', '0005_remove_additional')
    ]

    operations = [
        migrations.RunPython(convert_all_images)
    ]
