# Generated by Django 2.0.5 on 2018-07-14 05:11
# Set all wines with viticultural area "Bordeaux (White)" to "Bordeaux (white)"
# until a better Bordeaux viticultural area scheme is decided.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinoteca', '0008_rm_rueda_dups'),
    ]

    operations = [
        migrations.RunSQL([
            """update wines
               set type_id = (
                  select 
                    id
                  from wine_types
                  where type_name = 'Bordeaux (white)'
               ) 
               where id = (
                  select 
                    id
                  from wine_types
                  where type_name = 'Bordeaux (White)'
               );""",
            # Delete old wine type
            """delete from wine_types  
               where id = (
                  select 
                    id
                  from wine_types
                  where type_name = 'Bordeaux (White)'
               );"""
        ])
    ]
