# Generated by Django 2.0.5 on 2018-07-26 00:40

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('vinoteca', '0009_consolidate_bordeaux'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='countries',
            table='regions',
        ),
    ]
