# Generated by Django 2.0.5 on 2018-07-19 22:38
# Fixes a lot of name inconsistencies that have been around for way to long

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinoteca', '0009_consolidate_bordeaux'),
    ]

    operations = [
        migrations.RunSQL([
            # Rename countries table to regions
            """alter table countries rename to 'regions';""",
            # Rename colors.color to colors.name for consistency
            """alter table colors rename to '_colors_old';""",
            """create table colors (
                  id INTEGER PRIMARY KEY AUTOINCREMENT,
                  name TEXT
            );""",
            """insert into colors (id, name) select id, color from _colors_old;""",
            """create unique index idx_colors_name on colors(name);""",
            """drop table _colors_old;""",
            # Rename producers.country_id to region_id
            """alter table producers rename to '_producers_old';""",
            """ CREATE TABLE producers (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    name TEXT,
                    region_id INTEGER,
                    CONSTRAINT producers_regions_id_fk FOREIGN KEY (region_id) REFERENCES regions (id) ON DELETE SET NULL ON UPDATE SET NULL
                );""",
            """insert into producers (id, name, region_id) select id, name, country_id from _producers_old;""",
            """drop index producers_name_uindex;""",
            """create UNIQUE INDEX producers_name_uindex ON producers (name);""",
            """CREATE INDEX producers_region_id_index ON producers (region_id);""",
            """drop table _producers_old;""",
            # Rename wine_types.type_name to name
            """alter table wine_types rename to '_wine_types_old';""",
            """create table wine_types (
                  id INTEGER PRIMARY KEY AUTOINCREMENT,
                  name TEXT
            );""",
            """insert into wine_types (id, name) select id, type_name from _wine_types_old;""",
            """create unique index idx_wine_types_name on wine_types(name);""",
            """drop table _wine_types_old;""",
        ])
    ]
