# Generated by Django 2.0.5 on 2018-07-26 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinoteca', '0010_auto_20180725_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name="Producers",
            name="country",
            field=models.ForeignKey("Countries", models.DO_NOTHING, db_column="region_id", null=True)
        ),
        migrations.RenameField(
            model_name="Producers",
            old_name="country",
            new_name="region"
        ),
    ]
