# Generated by Django 2.0.5 on 2018-07-26 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinoteca', '0011_auto_20180725_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winetypes',
            old_name='type_name',
            new_name='name',
        ),
    ]
