# Generated by Django 2.0.5 on 2018-07-26 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinoteca', '0012_auto_20180725_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colors',
            old_name='color',
            new_name='name',
        ),
    ]
