# Generated by Django 2.0.5 on 2018-07-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinoteca', '0013_auto_20180725_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='name',
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='name',
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='grapes',
            name='name',
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='producers',
            name='name',
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='stores',
            name='name',
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vitiareas',
            name='name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='wines',
            name='inventory',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='winetypes',
            name='name',
            field=models.TextField(db_index=True, unique=True),
        ),
    ]
