# Generated by Django 2.0.5 on 2018-07-26 01:01

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('vinoteca', '0014_auto_20180725_1956'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Countries',
            new_name='Regions',
        ),
    ]
