# Generated by Django 2.0.7 on 2018-08-04 19:16
# Create color types if they don't exist
from django.db import migrations

from vinoteca.models import Colors


def add_colors(_, __):
    Colors.objects.get_or_create(name="red")
    Colors.objects.get_or_create(name="white")
    Colors.objects.get_or_create(name="rosé")
    Colors.objects.get_or_create(name="dessert")
    Colors.objects.get_or_create(name="sparkling")
    Colors.objects.get_or_create(name="port")


class Migration(migrations.Migration):

    dependencies = [
        ('vinoteca', '0016_auto_20180725_2003'),
    ]

    operations = [
        migrations.RunPython(add_colors)
    ]
