# Generated by Django 2.1.7 on 2019-05-05 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinoteca', '0018_create_config_yaml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regions',
            name='is_us',
        ),
    ]
