# Generated by Django 2.2.4 on 2019-10-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinoteca', '0019_remove_regions_is_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wines',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
