# Generated by Django 2.1.14 on 2019-12-28 01:52
# Requires that all wines have a producer, color, and wine type. All producers
# must now have a region.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinoteca', '0020_auto_20191017_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producers',
            name='region',
            field=models.ForeignKey(db_column='region_id', on_delete=django.db.models.deletion.DO_NOTHING, to='vinoteca.Regions'),
        ),
        migrations.AlterField(
            model_name='wines',
            name='color',
            field=models.ForeignKey(db_column='color_id', on_delete=django.db.models.deletion.DO_NOTHING, to='vinoteca.Colors'),
        ),
        migrations.AlterField(
            model_name='wines',
            name='producer',
            field=models.ForeignKey(db_column='producer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='vinoteca.Producers'),
        ),
        migrations.AlterField(
            model_name='wines',
            name='wine_type',
            field=models.ForeignKey(db_column='wine_type_id', on_delete=django.db.models.deletion.DO_NOTHING, to='vinoteca.WineTypes'),
        ),
    ]
