-- Insert colors
INSERT INTO colors (name)
VALUES ('red') ON CONFLICT DO NOTHING;
INSERT INTO colors (name)
VALUES ('white') ON CONFLICT DO NOTHING;
INSERT INTO colors (name)
VALUES ('rosé') ON CONFLICT DO NOTHING;
INSERT INTO colors (name)
VALUES ('dessert') ON CONFLICT DO NOTHING;
INSERT INTO colors (name)
VALUES ('sparkling') ON CONFLICT DO NOTHING;
INSERT INTO colors (name)
VALUES ('port') ON CONFLICT DO NOTHING;
INSERT INTO colors (name)
VALUES ('cider') ON CONFLICT DO NOTHING;
