# Generated by Django 2.1.7 on 2019-07-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WineSearchResult',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('color', models.TextField()),
                ('producer', models.TextField()),
                ('region', models.TextField()),
                ('wine_type', models.TextField()),
                ('viti_area', models.TextField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WineTableWine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(null=True)),
                ('region', models.TextField()),
                ('producer', models.TextField()),
                ('name', models.TextField(null=True)),
                ('wine_type', models.TextField()),
                ('color', models.TextField()),
                ('inventory', models.IntegerField()),
                ('vintage', models.IntegerField(null=True)),
                ('viti_area', models.TextField(null=True)),
                ('viti_area_id', models.IntegerField(null=True)),
                ('region_id', models.IntegerField()),
                ('producer_id', models.IntegerField()),
                ('wine_type_id', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
