name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  FORCE_COLOR: true
  ROCKET_TEST_DB: ${{ secrets.ROCKET_TEST_DB }}

jobs:
  # Limit parallel jobs
  db-test-lock:
    name: Database lock
    runs-on: ubuntu-latest
    steps:
      - name: 'Block Concurrent Executions'
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 5
          # Wait on all jobs, not just those for the same branch
          same-branch-only: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  rust-build:
    name: Rust build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Build
        run: cargo build

  rust-test:
    needs: db-test-lock
    name: Rust test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Test
        run: cargo test

  rust-lint:
    name: Rust lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy
      - name: Lint
        run: cargo clippy

  js:
    name: JS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate contracts
      run: cargo run --bin gen_contracts
    - name: Build
      run: |
        cd web
        npm ci --dev
        npm run build
    - name: Test
      run: |
        cd web
        npm run test
    - name: Lint
      run: |
        cd web
        npm run lint
