name: Main

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  CI: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: bash scripts/build.sh
    - name: Test
      run: bash scripts/test.sh
    - name: Lint
      run: bash scripts/lint.sh
