name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  ROCKET_TEST_DB: ${{ secrets.ROCKET_TEST_DB }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build
    - name: Test
      run: cargo test
    - name: Lint
      run:
        - rustup component add clippy --toolchain nightly-x86_64-unknown-linux-gnu || return 0
        - cargo clippy
